services:
    sonata.admin.post:
        class: Dictionary\AdminBundle\Admin\WordAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Word" }
        arguments:
            - ~
            - Dictionary\DictionaryBundle\Entity\Word
            - ~