<?php

namespace Dictionary\DictionaryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * historyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryRepository extends EntityRepository
{

	public function getLatestSearched($user) {
		$histories = $this->createQueryBuilder('h')
			->select('h, word')
			->innerJoin('h.word', 'word')
			->where('h.user = :user')
			->setParameter('user', $user)
			->orderBy('h.lastSearch', 'DESC')
			->setMaxResults(10)
			->getQuery()
			->getResult();

		return $histories;
	}

	public function getSearchedByHits($user) {
		$historyByHits = $this->createQueryBuilder('h')
			->select('h, word')
			->innerJoin('h.word', 'word')
			->where('h.user = :user')
			->andWhere('h.hits >= :number')
			->setParameter('user', $user)
			->setParameter('number', 1)
			->addOrderBy('h.hits', 'DESC')
			->addOrderBy('h.updated', 'DESC')
			->setMaxResults(20)
			->getQuery()
			->getResult();

		return $historyByHits;
	}
}
