<?php

namespace Dictionary\DictionaryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MismatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MismatchRepository extends EntityRepository
{
}
