<?php

namespace Doctrine\Bundle\DoctrineBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PilesRepository extends EntityRepository
{
}
