<?php

namespace Acme\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * eng2srbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class eng2srbRepository extends EntityRepository
{
}
