<?php

namespace Joiz\HardcoreBundle\Tests\Helper;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-01 at 11:26:00.
 */
class TranslateManagerTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var ReactionItemHelper
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{

	}
}